### ISSUE TITLE
Fraud Illustration 

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/ethics-and-rri-resources#1]
### Proposal

A cartoon of a researcher engaging in some form of scientific fraud (e.g. falsification of results, p-hacking).
Purpose is to illustrate how irresponsible practices can diminish public trust in science, as well as leading to undesirable consequences for the researcher involved.

**Comment by JonnyLighthands** [comment]
![03_Fraud-01](https://user-images.githubusercontent.com/107988620/176663295-1e6e6e93-109a-4b25-9e3c-2acea86aeb43.png)

**Comment by ClauFischer** [comment]
Thanks Jonny!
