### ISSUE TITLE
Overwhelmed Illustration

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/ethics-and-rri-resources#3]
An illustration showing an individual becoming overwhelmed with notifications and technology (e.g. screentime, social media).

**Comment by JonnyLighthands** [comment]
![01_Overwhelmed-01](https://user-images.githubusercontent.com/107988620/174986781-2db96c1a-53ee-41f1-9f3f-1cfc069e193e.png)

**Comment by chrisdburr** [comment]
Thanks, @JonnyLighthands . I will add this to the main repository and mark this as completed.
