### ISSUE TITLE
Public trust in science sketch

### ISSUE THREAD

**Issue by ClauFischer** [alan-turing-institute/ethics-and-rri-resources#4]
This is a sketch for the public trust in science illustration
![02_public trust in science](https://user-images.githubusercontent.com/104078689/174986681-3107aa62-ca5a-4b1d-b1a3-d449071ada58.jpg)
.

**Comment by JonnyLighthands** [comment]
![Uploading Public Trust in Science-01.png…]()

**Comment by JonnyLighthands** [comment]
![Public Trust in Science-01](https://user-images.githubusercontent.com/107988620/178142237-286c58ae-379b-4693-a4d5-a35df79d06d0.png)

**Comment by chrisdburr** [comment]
@ClauFischer: can you confirm you are happy with this as the final image? I can add it to the repository and close this issue afterwards.

**Comment by ClauFischer** [comment]
@chrisdburr @JonnyLighthands I am happy with it!

**Comment by JonnyLighthands** [comment]
![Public Trust in Science-01](https://user-images.githubusercontent.com/107988620/179219678-c417f6f2-27c1-41be-a954-caf3ad6ce9f1.png)


HI @chrisdburr @ClauFischer 
I've made a few small tweaks to this. The files have been updated on Google Drive

**Comment by ClauFischer** [comment]
Thanks Jonny! is it possible to upload the new version here as well?

**Comment by JonnyLighthands** [comment]
![04_Public Trust in Science-01](https://user-images.githubusercontent.com/107988620/179223434-776e6b74-f4ed-4a57-b19b-d2248a9ecd80.png)


here you go @ClauFischer

**Comment by ClauFischer** [comment]
Thanks @JonnyLighthands
